### ISSUE TITLE
exits the cli when using with bun

### ISSUE THREAD

**Issue by rkDevguru47** [skeletonlabs/create-skeleton-app#43] opened 2023-09-09 17:00 UTC
when we press enter after choosing between the template option, it exits to the terminal instead of proceeding to select the themes to install. 

please look into this 

using wsl linux terminal for installing. and was trying bun to work with this. it runs but fails as i explained.

**Comment by endigo9740** [comment] 2023-09-09 17:19
@rkDevguru47 as far as I'm aware Bun just hit v1, so we'll mark this as a feature request. But I cannot promise we'll move forward with it.

**Comment by niktek** [comment] 2023-09-12 02:20
Not sure if Bun has pushed out an update, but it installs and runs fine for me on macOS:
<img width="802" alt="image" src="https://github.com/skeletonlabs/create-skeleton-app/assets/52020637/919dc4f7-38fa-4d97-84d3-4762a085b9c7">

Might also be a terminal issue if you are able to test with another one ?

**Comment by niktek** [comment] 2023-09-12 02:21
I'm going to close the issue here as CSA has been migrated into the monorepo https://github.com/skeletonlabs/skeleton/tree/dev/packages/create-skeleton-app if this is is still an issue, please re-open there.

**Comment by niktek** [comment] 2023-09-12 02:43
Annnnd we changed our minds, keeping issues here - but directing PR's there.  So please let us know if you are still encountering issues with Bun here.

**Comment by niktek** [comment] 2023-09-12 05:38
I've managed to see the issue when running it directly from the source (` bun index.js`) as opposed to using `bun create` - the problem is that it doesn't give me any errors to work with.

There also seems to be a PR that is looking to fix some issues for the astro CLI here https://github.com/oven-sh/bun/pull/5035.

**Comment by niktek** [comment] 2023-09-15 23:42
Latest version seems to have fixed the CSA issues - can't guarantee anything beyond that at this point.

**Closed as completed by niktek** 2023-09-15 23:42 UTC
Labels: feature request
